# Generated by Django 3.2.5 on 2021-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigsearch', '0002_remove_searchquery_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='searchquery',
        ),
    ]
