# Generated by Django 3.2.5 on 2021-07-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craigsearch', '0004_auto_20210722_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='craigsearch.searcharea'),
        ),
    ]
