# Generated by Django 3.2.5 on 2021-07-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigsearch', '0006_auto_20210722_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
