# Generated by Django 3.2.5 on 2021-07-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigsearch', '0007_searchquery_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='area',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='region',
        ),
    ]
